"""Init

Revision ID: 3bee130ded30
Revises:
Create Date: 2025-06-23 20:56:36.388390

"""

from __future__ import annotations

import traceback

import pgvector
import sqlalchemy as sa
from alembic import context, op
from edgy import monkay, run_sync
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "3bee130ded30"
down_revision = None
branch_labels = None
depends_on = None


def hash_to_identifier(key: str | bytes) -> str:
    from base64 import b32encode
    from hashlib import blake2b

    if isinstance(key, str):
        key = key.encode()
    return f"_{b32encode(blake2b(key, digest_size=16).digest()).decode().rstrip('=')}"


force_fields_nullable: list[tuple[str, str]] = []


def upgrade(engine_name: str = "") -> None:
    # hash_to_identifier adds already an "_"
    fn = globals().get(f"upgrade{hash_to_identifier(engine_name)}")
    if fn is not None:
        fn()


def downgrade(engine_name: str = "") -> None:
    # hash_to_identifier adds already an "_"
    fn = globals().get(f"downgrade{hash_to_identifier(engine_name)}")
    if fn is not None:
        fn()


def upgrade_ZLTGSQOZ566UATSNRB2Y5JTWOA():
    # Migration of:
    # main database
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product",
        sa.Column("name", sa.String(length=255), autoincrement=False, nullable=False),
        sa.Column("description", sa.Text(), autoincrement=False, nullable=False),
        sa.Column("price", sa.Float(), autoincrement=False, nullable=False),
        sa.Column(
            "category", sa.String(length=100), autoincrement=False, nullable=False
        ),
        sa.Column(
            "material", sa.String(length=255), autoincrement=False, nullable=False
        ),
        sa.Column("color", sa.String(length=255), autoincrement=False, nullable=False),
        sa.Column(
            "tags", postgresql.ARRAY(sa.String()), autoincrement=False, nullable=False
        ),
        sa.Column(
            "sizes", postgresql.ARRAY(sa.Integer()), autoincrement=False, nullable=False
        ),
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True
        ),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "name",
            "category",
            "material",
            "color",
            name="uc_IVITIR6TIJNOXCVFSYUMDEUM5M",
        ),
    )
    # ### end Alembic commands ###
    if not context.is_offline_mode():
        try:
            with monkay.instance.registry.with_async_env():
                run_sync(
                    monkay.instance.registry.apply_default_force_nullable_fields(
                        force_fields_nullable=force_fields_nullable,
                        filter_db_name="",
                        model_defaults={},
                    )
                )
        except Exception as exc:
            print("failure migrating defaults", exc)
            traceback.print_exception(exc)


def downgrade_ZLTGSQOZ566UATSNRB2Y5JTWOA():
    # Migration of:
    # main database
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("product")
    # ### end Alembic commands ###
